name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "d231a5da-9b04-43a7-8977-93412bc00a2d"
database_name = "newsnow"
database_id = ""
